<?php

return [
    'groups' => [
        'webinar_default' => [
            'webinar_attended_nurture',
            'webinar_missed_nurture',
        ],
        'mortgage_default' => [
            'webinar_attended_nurture',
            'webinar_missed_nurture',
            'mortgage_homebuyer_nurture',
        ],
    ],
    'definitions' => [
        'webinar_attended_nurture' => [
            'key' => 'webinar_attended_nurture',
            'name' => 'Webinar Attended Nurture',
            'description' => 'Temporary staging smoke-test marketing nurture sequence for leads who attended a webinar but have not yet taken the next step. Restore the normal sequence after smoke testing.',
            'channel' => 'email',
            'purpose' => 'marketing',
            'scope' => 'webinar_nurture',
            'status' => 'active',
            'is_active' => true,
            'source_version' => 'staging_smoke_2026_07',
            'meta' => [
                'domain' => 'webinar',
                'strategy' => 'staging_smoke_short_interval',
                'temporary' => true,
                'notes' => 'This temporarily replaces the default attended nurture for staging smoke testing. Restore the normal default after smoke testing.',
            ],
            'steps' => [
                [
                    'step_number' => 1,
                    'name' => 'Smoke attended email step 1',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 10]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'webinar_nurture',
                ],
                [
                    'step_number' => 2,
                    'name' => 'Smoke attended email step 2',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 2]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'webinar_nurture',
                ],
                [
                    'step_number' => 3,
                    'name' => 'Smoke attended email step 3',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 2]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'webinar_nurture',
                ],
                [
                    'step_number' => 4,
                    'name' => 'Smoke attended email step 4',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 2]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'webinar_nurture',
                ],
                [
                    'step_number' => 5,
                    'name' => 'Smoke attended email step 5',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 2]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'webinar_nurture',
                ],
            ],
        ],
        'webinar_missed_nurture' => [
            'key' => 'webinar_missed_nurture',
            'name' => 'Webinar Missed Nurture',
            'description' => 'Default marketing nurture sequence for leads who registered for a webinar but missed it.',
            'channel' => 'email',
            'purpose' => 'marketing',
            'scope' => 'webinar_nurture',
            'status' => 'active',
            'is_active' => true,
            'source_version' => 3,
            'meta' => [
                'domain' => 'webinar',
                'strategy' => 'email_primary_sms_supplemental',
                'notes' => 'Transactional replay delivery belongs to Webinars. This campaign handles later marketing nurture only.',
            ],
            'steps' => [
                [
                    'step_number' => 1,
                    'name' => 'Missed webinar next step',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'hours' => 2]],
                    'meta' => ['type' => 'message'],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'webinar_nurture',
                ],
                [
                    'step_number' => 2,
                    'name' => 'Missed webinar next class invite',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'days' => 3]],
                    'meta' => ['type' => 'message'],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'webinar_nurture',
                ],
                [
                    'step_number' => 3,
                    'name' => 'Missed webinar long-term handoff',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'days' => 7]],
                    'meta' => ['type' => 'message'],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'webinar_nurture',
                ],
            ],
        ],
        'mortgage_homebuyer_nurture' => [
            'key' => 'mortgage_homebuyer_nurture',
            'name' => 'Mortgage Homebuyer Nurture',
            'description' => 'Default long-term mortgage homebuyer education sequence for leads who are not ready immediately.',
            'channel' => 'email',
            'purpose' => 'marketing',
            'scope' => 'mortgage_homebuyer_nurture',
            'status' => 'active',
            'is_active' => true,
            'source_version' => 3,
            'meta' => [
                'domain' => 'mortgage',
                'strategy' => 'email_primary_sms_supplemental',
                'notes' => 'Mortgage-specific nurture. Only sync this through mortgage preset groups.',
            ],
            'steps' => [
                [
                    'step_number' => 1,
                    'name' => 'Preparation basics',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'days' => 14]],
                    'meta' => ['type' => 'message'],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'mortgage_homebuyer_nurture',
                ],
                [
                    'step_number' => 2,
                    'name' => 'Timeline education',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'days' => 45]],
                    'meta' => ['type' => 'message'],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'mortgage_homebuyer_nurture',
                ],
                [
                    'step_number' => 3,
                    'name' => 'Soft reactivation',
                    'dispatch_key' => 'campaign_step_due',
                    'is_active' => true,
                    'criteria' => ['timing' => ['type' => 'delay', 'days' => 90]],
                    'meta' => ['type' => 'message'],
                    'channel' => 'email',
                    'purpose' => 'marketing',
                    'scope' => 'mortgage_homebuyer_nurture',
                ],
            ],
        ],
    ],
];
