<?php

return [
    'groups' => [
        'webinar_default' => [
            'webinar_attended_nurture',
            'webinar_missed_nurture',
        ],
        'mortgage_default' => [
            'webinar_attended_nurture',
            'webinar_missed_nurture',
        ],
    ],
    'definitions' => [
        'webinar_attended_nurture' => [
            'key' => 'webinar_attended_nurture',
            'name' => 'Webinar Attended Nurture',
            'description' => 'Temporary staging smoke-test marketing nurture sequence for leads who attended a webinar but have not yet taken the next step. Restore the normal sequence after smoke testing.',
            'channel' => 'email',
            'purpose' => 'marketing',
            'scope' => 'webinar_nurture',
            'status' => 'active',
            'is_active' => true,
            'source_version' => '1',
            'meta' => [
                'domain' => 'webinar',
                'strategy' => 'staging_smoke_short_interval',
                'temporary' => true,
                'notes' => 'This temporarily replaces the default attended nurture for staging smoke testing. Restore the normal default after smoke testing.',
            ],
            'steps' => [
                [
                    'step_number' => 1,
                    'name' => 'Smoke attended step 1',
                    'variant_strategy' => 'send_all_eligible',
                    'is_active' => true,
                    'source_version' => '1',
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 10]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'variants' => [
                        [
                            'key' => 'email',
                            'name' => 'Email follow-up',
                            'channel' => 'email',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.email.marketing.webinar_nurture.campaigns.webinar_attended_nurture.steps.1.variants.email',
                        ],
                        [
                            'key' => 'sms',
                            'name' => 'SMS follow-up',
                            'channel' => 'sms',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.sms.marketing.webinar_nurture.campaigns.webinar_attended_nurture.steps.1.variants.sms',
                        ],
                    ],
                ],
                [
                    'step_number' => 2,
                    'name' => 'Smoke attended step 2',
                    'variant_strategy' => 'send_all_eligible',
                    'is_active' => true,
                    'source_version' => '1',
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 2]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'variants' => [
                        [
                            'key' => 'email',
                            'name' => 'Email follow-up',
                            'channel' => 'email',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.email.marketing.webinar_nurture.campaigns.webinar_attended_nurture.steps.2.variants.email',
                        ],
                    ],
                ],
                [
                    'step_number' => 3,
                    'name' => 'Smoke attended step 3',
                    'variant_strategy' => 'send_all_eligible',
                    'is_active' => true,
                    'source_version' => '1',
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 2]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'variants' => [
                        [
                            'key' => 'email',
                            'name' => 'Email follow-up',
                            'channel' => 'email',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.email.marketing.webinar_nurture.campaigns.webinar_attended_nurture.steps.3.variants.email',
                        ],
                    ],
                ],
                [
                    'step_number' => 4,
                    'name' => 'Smoke attended step 4',
                    'variant_strategy' => 'send_all_eligible',
                    'is_active' => true,
                    'source_version' => '1',
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 2]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'variants' => [
                        [
                            'key' => 'email',
                            'name' => 'Email follow-up',
                            'channel' => 'email',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.email.marketing.webinar_nurture.campaigns.webinar_attended_nurture.steps.4.variants.email',
                        ],
                    ],
                ],
                [
                    'step_number' => 5,
                    'name' => 'Smoke attended step 5',
                    'variant_strategy' => 'send_all_eligible',
                    'is_active' => true,
                    'source_version' => '1',
                    'criteria' => ['timing' => ['type' => 'delay', 'minutes' => 2]],
                    'meta' => ['type' => 'message', 'temporary' => true],
                    'variants' => [
                        [
                            'key' => 'email',
                            'name' => 'Email follow-up',
                            'channel' => 'email',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.email.marketing.webinar_nurture.campaigns.webinar_attended_nurture.steps.5.variants.email',
                        ],
                    ],
                ],
            ],
        ],
        'webinar_missed_nurture' => [
            'key' => 'webinar_missed_nurture',
            'name' => 'Webinar Missed Nurture',
            'description' => 'Default marketing nurture sequence for leads who registered for a webinar but missed it.',
            'channel' => 'email',
            'purpose' => 'marketing',
            'scope' => 'webinar_nurture',
            'status' => 'active',
            'is_active' => true,
            'source_version' => '1',
            'meta' => [
                'domain' => 'webinar',
                'strategy' => 'email_primary_sms_supplemental',
                'notes' => 'Transactional replay delivery belongs to Webinars. This campaign handles later marketing nurture only.',
            ],
            'steps' => [
                [
                    'step_number' => 1,
                    'name' => 'Missed webinar next step',
                    'variant_strategy' => 'send_all_eligible',
                    'is_active' => true,
                    'source_version' => '1',
                    'criteria' => ['timing' => ['type' => 'delay', 'hours' => 2]],
                    'meta' => ['type' => 'message'],
                    'variants' => [
                        [
                            'key' => 'email',
                            'name' => 'Email follow-up',
                            'channel' => 'email',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.email.marketing.webinar_nurture.campaigns.webinar_missed_nurture.steps.1.variants.email',
                        ],
                        [
                            'key' => 'sms',
                            'name' => 'SMS follow-up',
                            'channel' => 'sms',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.sms.marketing.webinar_nurture.campaigns.webinar_missed_nurture.steps.1.variants.sms',
                        ],
                    ],
                ],
                [
                    'step_number' => 2,
                    'name' => 'Missed webinar next class invite',
                    'variant_strategy' => 'send_all_eligible',
                    'is_active' => true,
                    'source_version' => '1',
                    'criteria' => ['timing' => ['type' => 'delay', 'days' => 3]],
                    'meta' => ['type' => 'message'],
                    'variants' => [
                        [
                            'key' => 'email',
                            'name' => 'Email follow-up',
                            'channel' => 'email',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.email.marketing.webinar_nurture.campaigns.webinar_missed_nurture.steps.2.variants.email',
                        ],
                    ],
                ],
                [
                    'step_number' => 3,
                    'name' => 'Missed webinar long-term handoff',
                    'variant_strategy' => 'send_all_eligible',
                    'is_active' => true,
                    'source_version' => '1',
                    'criteria' => ['timing' => ['type' => 'delay', 'days' => 7]],
                    'meta' => ['type' => 'message'],
                    'variants' => [
                        [
                            'key' => 'email',
                            'name' => 'Email follow-up',
                            'channel' => 'email',
                            'purpose' => 'marketing',
                            'scope' => 'webinar_nurture',
                            'dispatch_key' => 'campaign_step_due',
                            'is_active' => true,
                            'source_config_path' => 'messaging.email.marketing.webinar_nurture.campaigns.webinar_missed_nurture.steps.3.variants.email',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
