<?php

return [
    'groups' => [
        'webinar_default' => [
            'webinar_attended_status_transition',
            'webinar_missed_status_transition',
            'webinar_attended_campaign_enrollment',
            'webinar_missed_campaign_enrollment',
        ],
        'mortgage_default' => [
            'webinar_attended_status_transition',
            'webinar_missed_status_transition',
            'webinar_attended_campaign_enrollment',
            'webinar_missed_campaign_enrollment',
            'smoke_webinar_attended_nurture_test_enrollment',
            'smoke_prospect_cancel_nurture_and_create_task',
        ],
    ],
    'definitions' => [
        'webinar_attended_status_transition' => [
            'key' => 'webinar_attended_status_transition',
            'trigger' => ['type' => 'automation_event', 'event_key' => 'webinar.attended'],
            'name' => 'Webinar Attended Status Transition',
            'version' => 1,
            'is_active' => true,
            'source_version' => 'client_readiness_2026_07',
            'meta' => ['description' => 'Move contacts who attended a webinar into the attended_webinar workflow status.', 'category' => 'webinar', 'default_role' => 'status_transition'],
            'points' => [[
                'key' => 'change_status_to_attended_webinar',
                'type' => 'change_status',
                'name' => 'Change Status to Attended Webinar',
                'description' => 'Move the contact into the attended_webinar status after a webinar.attended event.',
                'default_definition' => ['contact_status_key' => 'attended_webinar', 'reason' => 'webinar_attended_event', 'force' => false, 'on_same_status' => 'skipped', 'meta' => ['source' => 'flow_route', 'trigger_type' => 'automation_event', 'event_key' => 'webinar.attended']],
                'default_settings' => [],
                'is_active' => true,
                'source_version' => 'client_readiness_2026_07',
                'meta' => ['description' => 'Status transition point for attended webinar outcomes.'],
                'sort_order' => 1,
                'cancel_conditions' => [],
                'is_start' => true,
            ]],
        ],
        'webinar_missed_status_transition' => [
            'key' => 'webinar_missed_status_transition',
            'trigger' => ['type' => 'automation_event', 'event_key' => 'webinar.missed'],
            'name' => 'Webinar Missed Status Transition',
            'version' => 1,
            'is_active' => true,
            'source_version' => 'client_readiness_2026_07',
            'meta' => ['description' => 'Move contacts who missed a webinar into the missed_webinar workflow status.', 'category' => 'webinar', 'default_role' => 'status_transition'],
            'points' => [[
                'key' => 'change_status_to_missed_webinar',
                'type' => 'change_status',
                'name' => 'Change Status to Missed Webinar',
                'description' => 'Move the contact into the missed_webinar status after a webinar.missed event.',
                'default_definition' => ['contact_status_key' => 'missed_webinar', 'reason' => 'webinar_missed_event', 'force' => false, 'on_same_status' => 'skipped', 'meta' => ['source' => 'flow_route', 'trigger_type' => 'automation_event', 'event_key' => 'webinar.missed']],
                'default_settings' => [],
                'is_active' => true,
                'source_version' => 'client_readiness_2026_07',
                'meta' => ['description' => 'Status transition point for missed webinar outcomes.'],
                'sort_order' => 1,
                'cancel_conditions' => [],
                'is_start' => true,
            ]],
        ],
        'webinar_attended_campaign_enrollment' => [
            'key' => 'webinar_attended_campaign_enrollment',
            'trigger' => ['type' => 'automation_event', 'event_key' => 'webinar.attended'],
            'name' => 'Webinar Attended Follow-Up',
            'version' => 1,
            'is_active' => true,
            'source_version' => 'phase_19_default',
            'meta' => ['description' => 'Enroll contacts who attended a webinar into the attended nurture campaign.', 'category' => 'webinar', 'default_role' => 'campaign_enrollment'],
            'points' => [[
                'key' => 'enroll_webinar_attended_nurture',
                'type' => 'enroll_campaign',
                'name' => 'Enroll Webinar Attended Nurture',
                'description' => 'Enroll the contact into the attended webinar nurture campaign.',
                'default_definition' => ['campaign_key' => 'webinar_attended_nurture', 'on_already_enrolled' => 'skipped', 'payload' => [], 'meta' => ['source' => 'flow_route', 'reason' => 'webinar_attended_event'], 'start_context' => ['source' => 'flow_route', 'trigger_type' => 'automation_event', 'event_key' => 'webinar.attended'], 'exit_conditions' => []],
                'default_settings' => [],
                'is_active' => true,
                'source_version' => 'phase_19_default',
                'meta' => ['description' => 'Campaign enrollment point for attended webinar follow-up.'],
                'sort_order' => 1,
                'cancel_conditions' => [],
                'is_start' => true,
            ]],
        ],
        'webinar_missed_campaign_enrollment' => [
            'key' => 'webinar_missed_campaign_enrollment',
            'trigger' => ['type' => 'automation_event', 'event_key' => 'webinar.missed'],
            'name' => 'Webinar Missed Follow-Up',
            'version' => 1,
            'is_active' => true,
            'source_version' => 'phase_19_default',
            'meta' => ['description' => 'Enroll contacts who missed a webinar into the missed webinar nurture campaign.', 'category' => 'webinar', 'default_role' => 'campaign_enrollment'],
            'points' => [[
                'key' => 'enroll_webinar_missed_nurture',
                'type' => 'enroll_campaign',
                'name' => 'Enroll Webinar Missed Nurture',
                'description' => 'Enroll the contact into the missed webinar nurture campaign.',
                'default_definition' => ['campaign_key' => 'webinar_missed_nurture', 'on_already_enrolled' => 'skipped', 'payload' => [], 'meta' => ['source' => 'flow_route', 'reason' => 'webinar_missed_event'], 'start_context' => ['source' => 'flow_route', 'trigger_type' => 'automation_event', 'event_key' => 'webinar.missed'], 'exit_conditions' => []],
                'default_settings' => [],
                'is_active' => true,
                'source_version' => 'phase_19_default',
                'meta' => ['description' => 'Campaign enrollment point for missed webinar follow-up.'],
                'sort_order' => 1,
                'cancel_conditions' => [],
                'is_start' => true,
            ]],
        ],
        'smoke_webinar_attended_nurture_test_enrollment' => [
            'key' => 'smoke_webinar_attended_nurture_test_enrollment',
            'trigger' => ['type' => 'automation_event', 'event_key' => 'webinar.attended'],
            'name' => 'Disabled Legacy Smoke Webinar Attended Test Nurture Enrollment',
            'version' => 1,
            'is_active' => false,
            'source_version' => 'staging_smoke_2026_07_disabled',
            'meta' => ['description' => 'Disabled legacy disposable smoke route. The default webinar_attended_nurture route now carries the staging smoke timing.', 'category' => 'smoke_test', 'temporary' => true, 'disabled_reason' => 'default_attended_nurture_is_the_smoke_test'],
            'points' => [
                [
                    'key' => 'enroll_webinar_attended_nurture_email_test',
                    'type' => 'enroll_campaign',
                    'name' => 'Disabled Enroll Attended Email Test Nurture',
                    'description' => 'Disabled legacy smoke-test email campaign enrollment point.',
                    'default_definition' => ['campaign_key' => 'webinar_attended_nurture_email_test', 'on_already_enrolled' => 'skipped', 'payload' => [], 'meta' => ['source' => 'flow_route_smoke_test_disabled', 'reason' => 'disabled_legacy_smoke_route'], 'start_context' => [], 'exit_conditions' => []],
                    'default_settings' => [],
                    'is_active' => false,
                    'source_version' => 'staging_smoke_2026_07_disabled',
                    'meta' => ['description' => 'Disabled legacy smoke-test email campaign enrollment point.'],
                    'sort_order' => 1,
                    'is_start' => true,
                    'cancel_conditions' => [],
                ],
            ],
        ],
        'smoke_prospect_cancel_nurture_and_create_task' => [
            'key' => 'smoke_prospect_cancel_nurture_and_create_task',
            'contact_status_key' => 'prospect',
            'trigger' => ['type' => 'contact_status'],
            'name' => 'Prospect Cancels Attended Nurture and Creates Task',
            'version' => 1,
            'is_active' => true,
            'source_version' => 'staging_smoke_2026_07',
            'meta' => ['description' => 'Temporary staging route that cancels the active attended webinar nurture campaign and creates the prospect task.', 'category' => 'staging_smoke', 'temporary' => true],
            'points' => [
                [
                    'key' => 'smoke_cancel_attended_email_nurture',
                    'type' => 'cancel_campaign',
                    'name' => 'Cancel Attended Nurture',
                    'description' => 'Cancel the pending attended webinar nurture campaign when the contact becomes a prospect.',
                    'default_definition' => ['campaign_key' => 'webinar_attended_nurture', 'reason' => 'prospect_status_changed', 'skip_pending_messages' => true, 'on_not_enrolled' => 'completed', 'meta' => ['source' => 'flow_route_staging_smoke']],
                    'default_settings' => [],
                    'is_active' => true,
                    'source_version' => 'staging_smoke_2026_07',
                    'meta' => ['description' => 'Cancel active attended webinar nurture campaign.'],
                    'sort_order' => 1,
                    'is_start' => true,
                    'next_point_key' => 'smoke_create_prospect_task',
                    'cancel_conditions' => [],
                ],
                [
                    'key' => 'smoke_create_prospect_task',
                    'type' => 'create_task',
                    'name' => 'Create The Prospect Task',
                    'description' => 'Create and assign the prospect task after attended campaign cancellation.',
                    'default_definition' => ['task_template_key' => 'mortgage.call_lead', 'title' => 'The prospect task', 'description' => 'Smoke test prospect task created automatically after the contact status changes to Prospect.', 'assigned_to_strategy' => 'only_active_team_member', 'responsible_party' => 'internal', 'priority' => 'normal', 'meta' => ['source' => 'flow_route_staging_smoke', 'temporary' => true]],
                    'default_settings' => [],
                    'is_active' => true,
                    'source_version' => 'staging_smoke_2026_07',
                    'meta' => ['description' => 'Task creation point for the Prospect staging smoke route.'],
                    'sort_order' => 2,
                    'cancel_conditions' => [],
                ],
            ],
        ],
    ],
];

