<?php

return [
    'confirmation' => [
        'enabled' => true,
        'disableable' => true,
        'kind' => 'template',
        'label' => 'Registration confirmations',
        'description' => 'Sent after someone registers, using the registration message timing already owned by Webinars.',
        'purpose' => 'transactional',
        'scope' => 'webinar',
        'surface' => 'webinar_registrations',
        'message_type' => 'confirmation',
        'dispatch_key' => 'registration_created',
        'required' => true,
        'usage_types' => [
            'webinar_confirmation',
        ],
        'profile_context_keys' => [
            'confirmation',
            'confirmations',
        ],
        'sort_order' => 10,
    ],

    'registration_opt_in' => [
        'enabled' => true,
        'disableable' => false,
        'kind' => 'consent_acknowledgement',
        'label' => 'Registration opt-in confirmations',
        'description' => 'Messaging includes this acknowledgement with the registration confirmation when consolidation covers it; otherwise Messaging sends it separately.',
        'purpose' => 'transactional',
        'scope' => 'webinar',
        'surface' => 'webinar_registrations',
        'message_type' => 'opt_in',
        'dispatch_key' => 'consent_granted',
        'required' => 'registration_messaging_available',
        'usage_types' => [],
        'profile_context_keys' => [],
        'managed_by_messaging' => true,
        'consolidation_policy' => 'webinar_registration',
        'consolidation_primary' => [
            'area_key' => 'confirmation',
            'intent_key' => 'webinar.registration.confirmation',
            'purpose' => 'transactional',
            'scope' => 'webinar',
            'message_type' => 'confirmation',
            'dispatch_key' => 'registration_created',
        ],
        'sort_order' => 20,
    ],

    'reminders' => [
        'enabled' => true,
        'disableable' => true,
        'kind' => 'template',
        'label' => 'Reminder messages',
        'description' => 'Scheduled around the webinar start time. Changing the selected template affects future registrations only.',
        'purpose' => 'transactional',
        'scope' => 'webinar',
        'surface' => 'webinar_registrations',
        'message_type' => 'reminder',
        'dispatch_key' => 'registration_created',
        'required' => true,
        'usage_types' => [
            'webinar_reminder',
        ],
        'profile_context_keys' => [
            'reminder',
            'reminders',
        ],
        'sort_order' => 30,
    ],

    'waitlist' => [
        'enabled' => true,
        'disableable' => true,
        'kind' => 'template',
        'label' => 'Waitlist availability messages',
        'description' => 'Sent when a new webinar becomes available for people waiting on a series.',
        'purpose' => 'marketing',
        'scope' => 'webinar_waitlist',
        'surface' => 'webinar_waitlists',
        'message_type' => 'alert',
        'dispatch_key' => 'webinar_added',
        'required' => false,
        'usage_types' => [
            'webinar_waitlist_alert',
        ],
        'profile_context_keys' => [
            'waitlist',
        ],
        'sort_order' => 40,
    ],

    'waitlist_opt_in' => [
        'enabled' => true,
        'disableable' => false,
        'kind' => 'consent_acknowledgement',
        'label' => 'Waitlist opt-in confirmations',
        'description' => 'Messaging sends this acknowledgement when someone grants marketing messaging consent while joining a webinar waitlist.',
        'purpose' => 'marketing',
        'scope' => 'webinar_waitlist',
        'surface' => 'webinar_waitlists',
        'message_type' => 'opt_in',
        'dispatch_key' => 'consent_granted',
        'required' => 'waitlist_messaging_available',
        'usage_types' => [],
        'profile_context_keys' => [],
        'managed_by_messaging' => true,
        'sort_order' => 50,
    ],

    'post_attended' => [
        'enabled' => true,
        'disableable' => true,
        'kind' => 'template',
        'label' => 'Attended replay follow-up',
        'description' => 'Transactional replay follow-up for registrants marked as attended.',
        'purpose' => 'transactional',
        'scope' => 'webinar',
        'surface' => 'webinar_registrations',
        'message_type' => 'post_attended',
        'dispatch_key' => 'webinar_ended',
        'required' => true,
        'usage_types' => [
            'webinar_post_attended',
        ],
        'profile_context_keys' => [
            'post_attended',
        ],
        'sort_order' => 60,
    ],

    'post_missed' => [
        'enabled' => true,
        'disableable' => true,
        'kind' => 'template',
        'label' => 'Missed replay follow-up',
        'description' => 'Transactional replay follow-up for registrants marked as missed.',
        'purpose' => 'transactional',
        'scope' => 'webinar',
        'surface' => 'webinar_registrations',
        'message_type' => 'post_missed',
        'dispatch_key' => 'webinar_ended',
        'required' => true,
        'usage_types' => [
            'webinar_post_missed',
        ],
        'profile_context_keys' => [
            'post_missed',
        ],
        'sort_order' => 70,
    ],
];
