<?php

return [
    'format' => 'engage-core-project-state',
    'version' => 2,

    /*
    |--------------------------------------------------------------------------
    | Owner-only access
    |--------------------------------------------------------------------------
    |
    | The project-state surface is intentionally unavailable until an exact CRM
    | user email is configured. Keep this value in the selected client's .env.
    |
    */
    'authorized_email' => env('PROJECT_STATE_ADMIN_EMAIL'),

    'max_upload_kilobytes' => 102400,
    'enforce_client_key' => true,

    /*
    |--------------------------------------------------------------------------
    | Current-format state sections
    |--------------------------------------------------------------------------
    |
    | This is the importer's current contract. Older exports are transformed by
    | an external script before they are uploaded to the current application.
    |
    | Tables appear in dependency-safe import order. Runtime tables use
    | insert_empty and preserve their IDs. Preset-populated definition tables
    | use stable upsert identities, remap source foreign keys to target IDs, and
    | restore circular current-version pointers after their versions exist.
    |
    */
    'sections' => [
        'core' => [
            'version' => 1,
            'tables' => [
                'contact_statuses' => [
                    'mode' => 'upsert',
                    'identity' => ['key'],
                    'preserve_id' => false,
                    'order_by' => ['key'],
                    'columns' => [
                        'id',
                        'key',
                        'name',
                        'description',
                        'category',
                        'color',
                        'is_core',
                        'is_active',
                        'is_customized',
                        'customized_at',
                        'sort_order',
                        'source_version',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                ],

                'contact_import_batches' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'name',
                        'source',
                        'original_filename',
                        'status',
                        'imported_at',
                        'contact_count',
                        'successful_count',
                        'failed_count',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                ],

                'contacts' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'first_name',
                        'last_name',
                        'name',
                        'email',
                        'phone',
                        'source',
                        'subsource',
                        'contact_import_batch_id',
                        'last_contacted_at',
                        'last_activity_at',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                    'references' => [
                        'contact_import_batch_id' => 'contact_import_batches',
                    ],
                ],

                'contact_tags' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'contact_id',
                        'tag',
                        'created_at',
                        'updated_at',
                    ],
                    'references' => [
                        'contact_id' => 'contacts',
                    ],
                ],

                'notes' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'contact_id',
                        'related_type',
                        'related_id',
                        'body',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                    'references' => [
                        'contact_id' => 'contacts',
                    ],
                ],

                'site_settings' => [
                    'mode' => 'upsert',
                    'identity' => ['key'],
                    'preserve_id' => false,
                    'order_by' => ['key'],
                    'columns' => [
                        'id',
                        'key',
                        'value',
                        'created_at',
                        'updated_at',
                    ],
                ],
            ],
        ],

        'messaging' => [
            'version' => 1,
            'tables' => [
                'message_template_presets' => [
                    'mode' => 'upsert',
                    'identity' => ['key'],
                    'preserve_id' => false,
                    'order_by' => ['key'],
                    'columns' => [
                        'id',
                        'key',
                        'name',
                        'description',
                        'channel',
                        'purpose',
                        'scope',
                        'message_type',
                        'payload_class',
                        'queue',
                        'dispatch_keys',
                        'payload',
                        'tokens',
                        'status',
                        'is_active',
                        'source',
                        'source_config_path',
                        'source_version',
                        'is_customized',
                        'customized_at',
                        'last_synced_at',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => [
                        'dispatch_keys',
                        'payload',
                        'tokens',
                        'meta',
                    ],
                ],

                'message_template_preset_assignments' => [
                    'mode' => 'upsert',
                    'identity' => [
                        'message_template_preset_id',
                        'channel',
                        'purpose',
                        'scope',
                        'surface',
                        'message_type',
                        'definition_key',
                        'campaign_key',
                        'campaign_step',
                        'campaign_step_variant_key',
                        'context_type',
                        'context_id',
                    ],
                    'nullable_identity' => [
                        'surface',
                        'message_type',
                        'definition_key',
                        'campaign_key',
                        'campaign_step',
                        'campaign_step_variant_key',
                        'context_type',
                        'context_id',
                    ],
                    'preserve_id' => false,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'message_template_preset_id',
                        'channel',
                        'purpose',
                        'scope',
                        'surface',
                        'message_type',
                        'definition_key',
                        'campaign_key',
                        'campaign_step',
                        'campaign_step_variant_key',
                        'source_config_path',
                        'context_type',
                        'context_id',
                        'is_active',
                        'starts_at',
                        'ends_at',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                    'references' => [
                        'message_template_preset_id' => 'message_template_presets',
                    ],
                ],

                'message_template_catalog_entries' => [
                    'mode' => 'upsert',
                    'identity' => [
                        'message_template_preset_id',
                        'item_key',
                    ],
                    'preserve_id' => false,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'message_template_preset_id',
                        'channel',
                        'purpose',
                        'scope',
                        'module_key',
                        'module_label',
                        'surface',
                        'group_key',
                        'group_label',
                        'item_key',
                        'item_label',
                        'item_order',
                        'usage_type',
                        'source',
                        'source_config_path',
                        'context_type',
                        'context_id',
                        'is_active',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                    'references' => [
                        'message_template_preset_id' => 'message_template_presets',
                    ],
                ],

                'message_templates' => [
                    'mode' => 'upsert',
                    'identity' => ['key'],
                    'preserve_id' => false,
                    'order_by' => ['key'],
                    'columns' => [
                        'id',
                        'key',
                        'name',
                        'description',
                        'channel',
                        'status',
                        'current_version_id',
                        'source',
                        'source_version',
                        'is_customized',
                        'customized_at',
                        'created_at',
                        'updated_at',
                    ],
                    'deferred_references' => [
                        'current_version_id' => 'message_template_versions',
                    ],
                ],

                'message_template_versions' => [
                    'mode' => 'upsert',
                    'identity' => [
                        'message_template_id',
                        'version',
                    ],
                    'preserve_id' => false,
                    'order_by' => ['message_template_id', 'version'],
                    'columns' => [
                        'id',
                        'message_template_id',
                        'version',
                        'subject',
                        'content',
                        'renderer_key',
                        'renderer_version',
                        'content_hash',
                        'created_by',
                        'created_at',
                    ],
                    'json_columns' => ['content'],
                    'references' => [
                        'message_template_id' => 'message_templates',
                    ],
                    'null_on_import' => ['created_by'],
                ],

                'message_chains' => [
                    'mode' => 'upsert',
                    'identity' => ['key'],
                    'preserve_id' => false,
                    'order_by' => ['key'],
                    'columns' => [
                        'id',
                        'key',
                        'name',
                        'description',
                        'status',
                        'current_version_id',
                        'source',
                        'source_version',
                        'is_customized',
                        'customized_at',
                        'created_at',
                        'updated_at',
                    ],
                    'deferred_references' => [
                        'current_version_id' => 'message_chain_versions',
                    ],
                ],

                'message_chain_versions' => [
                    'mode' => 'upsert',
                    'identity' => [
                        'message_chain_id',
                        'version',
                    ],
                    'preserve_id' => false,
                    'order_by' => ['message_chain_id', 'version'],
                    'columns' => [
                        'id',
                        'message_chain_id',
                        'version',
                        'exit_conditions',
                        'content_hash',
                        'published_at',
                        'created_by',
                        'created_at',
                    ],
                    'json_columns' => ['exit_conditions'],
                    'references' => [
                        'message_chain_id' => 'message_chains',
                    ],
                    'null_on_import' => ['created_by'],
                ],

                'message_chain_steps' => [
                    'mode' => 'upsert',
                    'identity' => [
                        'message_chain_version_id',
                        'key',
                    ],
                    'preserve_id' => false,
                    'order_by' => ['message_chain_version_id', 'sort_order', 'id'],
                    'columns' => [
                        'id',
                        'message_chain_version_id',
                        'key',
                        'name',
                        'sort_order',
                        'timing_type',
                        'anchor_key',
                        'offset_seconds',
                        'day_offset',
                        'local_time',
                        'variant_strategy',
                        'advance_policy',
                        'conditions',
                        'is_active',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['conditions'],
                    'references' => [
                        'message_chain_version_id' => 'message_chain_versions',
                    ],
                ],

                'message_chain_step_variants' => [
                    'mode' => 'upsert',
                    'identity' => [
                        'message_chain_step_id',
                        'key',
                    ],
                    'preserve_id' => false,
                    'order_by' => ['message_chain_step_id', 'sort_order', 'id'],
                    'columns' => [
                        'id',
                        'message_chain_step_id',
                        'key',
                        'sort_order',
                        'message_template_version_id',
                        'channel',
                        'purpose',
                        'scope',
                        'message_type',
                        'queue',
                        'dependency_policy',
                        'conditions',
                        'is_active',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => [
                        'dependency_policy',
                        'conditions',
                    ],
                    'references' => [
                        'message_chain_step_id' => 'message_chain_steps',
                        'message_template_version_id' => 'message_template_versions',
                    ],
                ],

                'message_consents' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'contact_id',
                        'channel',
                        'purpose',
                        'scope',
                        'consented_at',
                        'source',
                        'ip_address',
                        'user_agent',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                    'references' => [
                        'contact_id' => 'contacts',
                    ],
                ],

                'consent_revocations' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'contact_id',
                        'message_consent_id',
                        'channel',
                        'purpose',
                        'scope',
                        'reason',
                        'revoked_at',
                        'source',
                        'ip_address',
                        'user_agent',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                    'references' => [
                        'contact_id' => 'contacts',
                        'message_consent_id' => 'message_consents',
                    ],
                ],

                'message_suppressions' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'channel',
                        'destination',
                        'reason',
                        'provider',
                        'source_event_id',
                        'suppressed_at',
                        'released_at',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['meta'],
                ],

                'message_chain_enrollments' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'message_chain_version_id',
                        'recipient_type',
                        'recipient_id',
                        'context_type',
                        'context_id',
                        'origin_type',
                        'origin_id',
                        'surface',
                        'current_message_chain_step_id',
                        'next_action_at',
                        'status',
                        'dedupe_key',
                        'started_at',
                        'paused_at',
                        'resumed_at',
                        'exited_at',
                        'exit_reason_code',
                        'completed_at',
                        'cancelled_at',
                        'created_at',
                        'updated_at',
                    ],
                    'references' => [
                        'message_chain_version_id' => 'message_chain_versions',
                        'current_message_chain_step_id' => 'message_chain_steps',
                    ],
                    'import_value_maps' => [
                        'status' => [
                            'active' => 'paused',
                        ],
                    ],
                ],

                'scheduled_messages' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'recipient_type',
                        'recipient_id',
                        'context_type',
                        'context_id',
                        'behavior_owner_type',
                        'behavior_owner_id',
                        'channel',
                        'message_type',
                        'purpose',
                        'scope',
                        'payload_class',
                        'queue',
                        'dispatch_keys',
                        'definition_config_path',
                        'payload',
                        'send_at',
                        'status',
                        'provider_idempotency_key',
                        'dedupe_key',
                        'meta',
                        'created_at',
                        'updated_at',
                        'message_template_version_id',
                        'message_chain_enrollment_id',
                        'message_chain_step_variant_id',
                    ],
                    'json_columns' => [
                        'dispatch_keys',
                        'payload',
                        'meta',
                    ],
                    'references' => [
                        'message_template_version_id' => 'message_template_versions',
                        'message_chain_enrollment_id' => 'message_chain_enrollments',
                        'message_chain_step_variant_id' => 'message_chain_step_variants',
                    ],
                ],

                'contact_permission_invitations' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'contact_id',
                        'scheduled_message_id',
                        'token',
                        'context_type',
                        'context_id',
                        'channel',
                        'source',
                        'status',
                        'claimed_at',
                        'sent_at',
                        'failed_at',
                        'accepted_at',
                        'accepted_channels',
                        'failure_reason',
                        'meta',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => [
                        'accepted_channels',
                        'meta',
                    ],
                    'references' => [
                        'contact_id' => 'contacts',
                        'scheduled_message_id' => 'scheduled_messages',
                    ],
                ],

                'scheduled_message_render_contexts' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'scheduled_message_id',
                        'values',
                        'content_hash',
                        'rendered_at',
                        'expires_at',
                        'created_at',
                        'updated_at',
                    ],
                    'json_columns' => ['values'],
                    'references' => [
                        'scheduled_message_id' => 'scheduled_messages',
                    ],
                ],

                'scheduled_message_components' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['scheduled_message_id', 'sort_order', 'id'],
                    'columns' => [
                        'id',
                        'scheduled_message_id',
                        'message_template_version_id',
                        'role',
                        'intent_key',
                        'message_consent_id',
                        'sort_order',
                        'placement_key',
                        'created_at',
                        'updated_at',
                    ],
                    'references' => [
                        'scheduled_message_id' => 'scheduled_messages',
                        'message_template_version_id' => 'message_template_versions',
                        'message_consent_id' => 'message_consents',
                    ],
                ],

                'scheduled_message_delivery_attempts' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['scheduled_message_id', 'attempt_number', 'id'],
                    'columns' => [
                        'id',
                        'scheduled_message_id',
                        'attempt_number',
                        'claim_token',
                        'status',
                        'claimed_at',
                        'lease_expires_at',
                        'provider_submission_started_at',
                        'completed_at',
                        'destination',
                        'provider',
                        'provider_message_id',
                        'reason_code',
                        'reason',
                        'created_at',
                        'updated_at',
                    ],
                    'references' => [
                        'scheduled_message_id' => 'scheduled_messages',
                    ],
                    'import_value_maps' => [
                        'status' => [
                            'claimed' => 'paused',
                            'submitting' => 'paused',
                        ],
                    ],
                ],

                'scheduled_message_outbox_events' => [
                    'mode' => 'insert_empty',
                    'preserve_id' => true,
                    'order_by' => ['id'],
                    'columns' => [
                        'id',
                        'scheduled_message_id',
                        'delivery_attempt_id',
                        'event_type',
                        'occurred_at',
                        'reason_code',
                        'reason',
                        'status',
                        'available_at',
                        'claim_token',
                        'claim_expires_at',
                        'attempts',
                        'last_attempted_at',
                        'published_at',
                        'last_error',
                        'created_at',
                        'updated_at',
                    ],
                    'references' => [
                        'scheduled_message_id' => 'scheduled_messages',
                        'delivery_attempt_id' => 'scheduled_message_delivery_attempts',
                    ],
                    'import_value_maps' => [
                        'status' => [
                            'pending' => 'paused',
                            'processing' => 'paused',
                        ],
                    ],
                ],
            ],
        ],
    ],
];