<?php

return [
    'version' => 8,
    'tables' => [
        'campaigns' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['key'],
            'columns' => [
                'id',
                'key',
                'name',
                'description',
                'message_chain_id',
                'channel',
                'purpose',
                'scope',
                'status',
                'family_key',
                'priority',
                'eligibility_filter',
                'enrollment_mode',
                'reentry_policy',
                'ineligible_behavior',
                'source_version',
                'is_customized',
                'customized_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['eligibility_filter', 'meta'],
            'references' => [
                'message_chain_id' => 'message_chains',
            ],
        ],

        'campaign_steps' => [
            'mode' => 'upsert',
            'identity' => [
                'campaign_id',
                'step_number',
            ],
            'preserve_id' => false,
            'order_by' => ['campaign_id', 'step_number'],
            'columns' => [
                'id',
                'campaign_id',
                'step_number',
                'name',
                'dispatch_key',
                'channel',
                'purpose',
                'scope',
                'variant_strategy',
                'is_active',
                'criteria',
                'source_version',
                'is_customized',
                'customized_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'criteria',
                'meta',
            ],
            'references' => [
                'campaign_id' => 'campaigns',
            ],
        ],

        'campaign_step_variants' => [
            'mode' => 'upsert',
            'identity' => [
                'campaign_step_id',
                'key',
            ],
            'preserve_id' => false,
            'order_by' => ['campaign_step_id', 'sort_order', 'id'],
            'columns' => [
                'id',
                'campaign_step_id',
                'key',
                'name',
                'sort_order',
                'dispatch_key',
                'channel',
                'purpose',
                'scope',
                'is_active',
                'criteria',
                'dependency_rules',
                'source_config_path',
                'source_version',
                'is_customized',
                'customized_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'criteria',
                'dependency_rules',
                'meta',
            ],
            'references' => [
                'campaign_step_id' => 'campaign_steps',
            ],
        ],


        'campaign_touch_programs' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['key'],
            'columns' => [
                'id',
                'campaign_id',
                'key',
                'name',
                'audience_type',
                'audience_key',
                'recurrence',
                'repeat_years',
                'starts_on',
                'is_active',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'campaign_id' => 'campaigns',
            ],
        ],

        'campaign_touch_dates' => [
            'mode' => 'upsert',
            'identity' => [
                'campaign_touch_program_id',
                'key',
            ],
            'preserve_id' => false,
            'order_by' => ['campaign_touch_program_id', 'sort_order', 'id'],
            'columns' => [
                'id',
                'campaign_touch_program_id',
                'key',
                'name',
                'source_type',
                'source_key',
                'month',
                'day',
                'offset_days',
                'send_time',
                'sort_order',
                'is_active',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'campaign_touch_program_id' => 'campaign_touch_programs',
            ],
        ],

        'campaign_touch_variants' => [
            'mode' => 'upsert',
            'identity' => [
                'campaign_touch_date_id',
                'key',
            ],
            'preserve_id' => false,
            'order_by' => ['campaign_touch_date_id', 'sort_order', 'id'],
            'columns' => [
                'id',
                'campaign_touch_date_id',
                'key',
                'name',
                'sort_order',
                'channel',
                'purpose',
                'scope',
                'message_template_preset_id',
                'is_active',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'campaign_touch_date_id' => 'campaign_touch_dates',
                'message_template_preset_id' => 'message_template_presets',
            ],
        ],

        'campaign_touch_dispatches' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'campaign_touch_variant_id',
                'contact_id',
                'occurrence_year',
                'due_at',
                'scheduled_message_id',
                'status',
                'reason',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'campaign_touch_variant_id' => 'campaign_touch_variants',
                'contact_id' => 'contacts',
                'scheduled_message_id' => 'scheduled_messages',
            ],
        ],


        'campaign_eligibility_states' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'campaign_id',
                'contact_id',
                'is_eligible',
                'eligibility_cycle',
                'became_eligible_at',
                'became_ineligible_at',
                'last_evaluated_at',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'campaign_id' => 'campaigns',
                'contact_id' => 'contacts',
            ],
        ],

        'campaign_enrollments' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'contact_id',
                'campaign_id',
                'message_chain_enrollment_id',
                'source_type',
                'source_id',
                'campaign_key',
                'start_context',
                'dedupe_key',
                'started_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'start_context',
                'meta',
            ],
            'references' => [
                'contact_id' => 'contacts',
                'campaign_id' => 'campaigns',
                'message_chain_enrollment_id' => 'message_chain_enrollments',
            ],
            'polymorphic_references' => [
                [
                    'type_column' => 'source_type',
                    'id_column' => 'source_id',
                    'targets' => [
                        'App\\Modules\\Core\\Models\\Contact' => 'contacts',
                        'App\\Modules\\Core\\Models\\ContactImportOccurrence' => 'contact_import_occurrences',
                        'App\\Modules\\Webinars\\Models\\WebinarRegistration' => 'webinar_registrations',
                        'App\\Modules\\Webinars\\Models\\WebinarWaitlistSignup' => 'webinar_waitlist_signups',
                        'App\\Modules\\Webinars\\Models\\Webinar' => 'webinars',
                        'App\\Modules\\Webinars\\Models\\WebinarSeries' => 'webinar_series',
                        'App\\Modules\\FlowRoutes\\Models\\ContactFlowRouteProgress' => 'contact_flow_route_progress',
                    ],
                    'deferred' => true,
                ],
            ],
        ],
    ],
];