<?php

return [
    'version' => 1,
    'tables' => [
        'campaigns' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['key'],
            'columns' => [
                'id',
                'key',
                'name',
                'description',
                'channel',
                'purpose',
                'scope',
                'status',
                'source_version',
                'is_customized',
                'customized_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
        ],

        'campaign_steps' => [
            'mode' => 'upsert',
            'identity' => [
                'campaign_id',
                'step_number',
            ],
            'preserve_id' => false,
            'order_by' => ['campaign_id', 'step_number'],
            'columns' => [
                'id',
                'campaign_id',
                'step_number',
                'name',
                'dispatch_key',
                'channel',
                'purpose',
                'scope',
                'variant_strategy',
                'is_active',
                'criteria',
                'source_version',
                'is_customized',
                'customized_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'criteria',
                'meta',
            ],
            'references' => [
                'campaign_id' => 'campaigns',
            ],
        ],

        'campaign_step_variants' => [
            'mode' => 'upsert',
            'identity' => [
                'campaign_step_id',
                'key',
            ],
            'preserve_id' => false,
            'order_by' => ['campaign_step_id', 'sort_order', 'id'],
            'columns' => [
                'id',
                'campaign_step_id',
                'key',
                'name',
                'sort_order',
                'dispatch_key',
                'channel',
                'purpose',
                'scope',
                'is_active',
                'criteria',
                'dependency_rules',
                'source_config_path',
                'source_version',
                'is_customized',
                'customized_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'criteria',
                'dependency_rules',
                'meta',
            ],
            'references' => [
                'campaign_step_id' => 'campaign_steps',
            ],
        ],

        'campaign_enrollments' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'contact_id',
                'campaign_id',
                'source_type',
                'source_id',
                'campaign_key',
                'status',
                'current_step',
                'current_campaign_step_id',
                'start_context',
                'exit_conditions',
                'exited_at',
                'exit_reason',
                'last_scheduled_message_id',
                'dedupe_key',
                'started_at',
                'paused_at',
                'resumed_at',
                'cancelled_at',
                'completed_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'start_context',
                'exit_conditions',
                'meta',
            ],
            'references' => [
                'contact_id' => 'contacts',
                'campaign_id' => 'campaigns',
                'current_campaign_step_id' => 'campaign_steps',
                'last_scheduled_message_id' => 'scheduled_messages',
            ],
            'polymorphic_references' => [
                [
                    'type_column' => 'source_type',
                    'id_column' => 'source_id',
                    'targets' => [
                        'App\\Modules\\Webinars\\Models\\WebinarRegistration' => 'webinar_registrations',
                        'App\\Modules\\Webinars\\Models\\WebinarWaitlistSignup' => 'webinar_waitlist_signups',
                        'App\\Modules\\Webinars\\Models\\Webinar' => 'webinars',
                        'App\\Modules\\Webinars\\Models\\WebinarSeries' => 'webinar_series',
                    ],
                ],
            ],
            'import_value_maps' => [
                'status' => [
                    'active' => 'paused',
                ],
            ],
            'resume_items' => [
                [
                    'category' => 'campaign_enrollments',
                    'column' => 'status',
                    'statuses' => ['active'],
                ],
            ],
        ],
    ],
];