<?php

return [
    'version' => 1,
    'optional' => true,
    'activation_tables' => [
        'form_definitions',
        'form_versions',
        'form_submissions',
        'form_submission_values',
    ],
    'tables' => [
        'form_definitions' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['key'],
            'columns' => [
                'id',
                'key',
                'name',
                'description',
                'status',
                'category',
                'is_public',
                'current_form_version_id',
                'source',
                'provider',
                'external_id',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => ['meta'],
            'deferred_references' => [
                'current_form_version_id' => 'form_versions',
            ],
        ],

        'form_versions' => [
            'mode' => 'upsert',
            'identity' => [
                'form_definition_id',
                'version',
            ],
            'preserve_id' => false,
            'order_by' => [
                'form_definition_id',
                'version',
            ],
            'columns' => [
                'id',
                'form_definition_id',
                'version',
                'status',
                'name',
                'description',
                'schema',
                'rules',
                'layout',
                'settings',
                'published_at',
                'archived_at',
                'source',
                'provider',
                'external_id',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => [
                'schema',
                'rules',
                'layout',
                'settings',
                'meta',
            ],
            'references' => [
                'form_definition_id' => 'form_definitions',
            ],
        ],

        'form_submissions' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'form_definition_id',
                'form_version_id',
                'contact_id',
                'subject_type',
                'subject_id',
                'status',
                'review_status',
                'submitted_at',
                'reviewed_at',
                'reviewed_by_type',
                'reviewed_by_id',
                'source',
                'provider',
                'external_id',
                'ip_address',
                'user_agent',
                'payload',
                'raw_payload',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => [
                'payload',
                'raw_payload',
                'meta',
            ],
            'references' => [
                'form_definition_id' => 'form_definitions',
                'form_version_id' => 'form_versions',
                'contact_id' => 'contacts',
            ],
            'polymorphic_references' => [
                [
                    'type_column' => 'subject_type',
                    'id_column' => 'subject_id',
                    'targets' => [
                        'App\\Modules\\Core\\Models\\Contact' => 'contacts',
                    ],
                ],
            ],
            'null_on_import' => [
                'reviewed_by_type',
                'reviewed_by_id',
            ],
        ],

        'form_submission_values' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => [
                'form_submission_id',
                'sort_order',
                'id',
            ],
            'columns' => [
                'id',
                'form_submission_id',
                'field_key',
                'field_label',
                'field_type',
                'value',
                'value_text',
                'value_number',
                'value_boolean',
                'value_date',
                'value_datetime',
                'sort_order',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => [
                'value',
                'meta',
            ],
            'references' => [
                'form_submission_id' => 'form_submissions',
            ],
        ],
    ],
];