<?php

return [
    'version' => 7,
    'tables' => [
        'inbound_email_routes' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['key'],
            'columns' => [
                'id',
                'key',
                'local_part',
                'label',
                'source',
                'context_key',
                'is_active',
                'created_at',
                'updated_at',
            ],
        ],

        'inbound_reply_profiles' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['key'],
            'columns' => [
                'id',
                'key',
                'label',
                'description',
                'is_active',
                'source',
                'source_config_path',
                'source_version',
                'is_customized',
                'customized_at',
                'last_synced_at',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => ['meta'],
        ],

        'inbound_reply_intents' => [
            'mode' => 'upsert',
            'identity' => [
                'inbound_reply_profile_id',
                'key',
            ],
            'preserve_id' => false,
            'order_by' => ['inbound_reply_profile_id', 'sort_order', 'id'],
            'columns' => [
                'id',
                'inbound_reply_profile_id',
                'key',
                'label',
                'description',
                'is_active',
                'sort_order',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'inbound_reply_profile_id' => 'inbound_reply_profiles',
            ],
        ],

        'inbound_reply_rules' => [
            'mode' => 'upsert',
            'identity' => [
                'inbound_reply_intent_id',
                'match_type',
                'normalized_value',
            ],
            'preserve_id' => false,
            'order_by' => ['inbound_reply_intent_id', 'sort_order', 'id'],
            'columns' => [
                'id',
                'inbound_reply_intent_id',
                'match_type',
                'value',
                'normalized_value',
                'is_active',
                'sort_order',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'inbound_reply_intent_id' => 'inbound_reply_intents',
            ],
        ],

        'inbound_messages' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'webhook_inbox_receipt_id',
                'sender_type',
                'sender_id',
                'related_contact_id',
                'client_key',
                'channel',
                'provider',
                'provider_event_id',
                'provider_event_key',
                'provider_message_id',
                'provider_message_key',
                'provider_context_id',
                'message_id',
                'from_type',
                'from_value',
                'to_type',
                'to_value',
                'subject',
                'body',
                'classification',
                'purpose',
                'scope',
                'correlated_scheduled_message_id',
                'reply_intent_key',
                'reply_correlation_method',
                'inbound_email_route_key',
                'inbound_email_route_source',
                'inbound_email_route_context',
                'received_at',
                'processed_at',
                'inbox_status',
                'reviewed_at',
                'completed_at',
                'created_at',
                'updated_at',
            ],
            'null_on_import' => [
                'webhook_inbox_receipt_id',
            ],
            'references' => [
                'related_contact_id' => 'contacts',
            ],
            'deferred_references' => [
                'correlated_scheduled_message_id' => 'scheduled_messages',
            ],
            'polymorphic_references' => [
                [
                    'type_column' => 'sender_type',
                    'id_column' => 'sender_id',
                    'targets' => [
                        'App\\Modules\\Core\\Models\\Contact' => 'contacts',
                    ],
                ],
            ],
        ],
    ],
];