<?php

return [
    'version' => 1,
    'optional' => true,
    'activation_tables' => [
        'location_areas',
        'location_area_assignments',
    ],
    'tables' => [
        'location_areas' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['key'],
            'columns' => [
                'id',
                'key',
                'name',
                'description',
                'type',
                'status',
                'boundary_type',
                'country',
                'region',
                'city',
                'postal_code',
                'center_latitude',
                'center_longitude',
                'radius_meters',
                'geometry',
                'timezone',
                'is_service_area',
                'source',
                'provider',
                'external_id',
                'external_url',
                'settings',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => [
                'geometry',
                'settings',
                'meta',
            ],
        ],

        'location_area_assignments' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['location_area_id', 'subject_type', 'subject_id', 'role', 'id'],
            'columns' => [
                'id',
                'location_area_id',
                'location_id',
                'contact_id',
                'subject_type',
                'subject_id',
                'role',
                'status',
                'is_primary',
                'starts_at',
                'expires_at',
                'source',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'location_area_id' => 'location_areas',
                'contact_id' => 'contacts',
            ],
            'null_on_import' => ['location_id'],
            'polymorphic_references' => [
                [
                    'type_column' => 'subject_type',
                    'id_column' => 'subject_id',
                    'targets' => [
                        'App\\Modules\\Core\\Models\\Contact' => 'contacts',
                        'App\\Modules\\Relationships\\Models\\ContactRelationship' => 'contact_relationships',
                    ],
                ],
            ],
        ],
    ],
];