<?php

return [
    'version' => 2,
    'optional' => true,
    'activation_tables' => [
        'mortgage_stages',
        'contact_mortgage_profiles',
        'mortgage_loans',
        'mortgage_loan_participants',
        'mortgage_loan_realtors',
        'mortgage_realtor_profiles',
        'mortgage_realtor_markets',
        'mortgage_realtor_production_snapshots',
    ],
    'tables' => [
        'mortgage_stages' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['sort_order', 'key'],
            'columns' => [
                'id',
                'key',
                'name',
                'category',
                'is_active',
                'sort_order',
                'created_at',
                'updated_at',
            ],
        ],

        'contact_mortgage_profiles' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'contact_id',
                'has_realtor',
                'market_key',
                'original_lead_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'contact_id' => 'contacts',
            ],
        ],

        'mortgage_loans' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'mortgage_stage_id',
                'source_system',
                'source_record_id',
                'source_fingerprint',
                'loan_originator',
                'loan_purpose',
                'loan_program',
                'mortgage_type',
                'lien_position',
                'loan_amount',
                'note_rate',
                'sales_price',
                'appraised_value',
                'cash_to_close',
                'subject_property_street',
                'subject_property_city',
                'subject_property_state',
                'subject_property_zip',
                'closed_on',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'mortgage_stage_id' => 'mortgage_stages',
            ],
        ],

        'mortgage_loan_participants' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'mortgage_loan_id',
                'contact_id',
                'role',
                'position',
                'first_name',
                'last_name',
                'email',
                'phone',
                'date_of_birth',
                'mailing_address',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'mortgage_loan_id' => 'mortgage_loans',
                'contact_id' => 'contacts',
            ],
        ],

        'mortgage_loan_realtors' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'mortgage_loan_id',
                'contact_id',
                'role',
                'position',
                'name',
                'email',
                'phone',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'mortgage_loan_id' => 'mortgage_loans',
                'contact_id' => 'contacts',
            ],
        ],

        'mortgage_realtor_profiles' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'contact_relationship_id',
                'brokerage_name',
                'license_number',
                'last_referral_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'contact_relationship_id' => 'contact_relationships',
            ],
        ],

        'mortgage_realtor_markets' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'mortgage_realtor_profile_id',
                'market_key',
                'is_primary',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'mortgage_realtor_profile_id' => 'mortgage_realtor_profiles',
            ],
        ],

        'mortgage_realtor_production_snapshots' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'mortgage_realtor_profile_id',
                'period_ending_on',
                'period_months',
                'loan_count',
                'conventional_count',
                'va_count',
                'loan_volume',
                'source',
                'source_fingerprint',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'mortgage_realtor_profile_id' => 'mortgage_realtor_profiles',
            ],
        ],
    ],
];