<?php

return [
    'version' => 2,
    'optional' => true,
    'activation_tables' => [
        'reporting_sessions',
        'reporting_observations',
        'reporting_external_measurements',
        'reporting_daily_metrics',
        'reporting_projection_checkpoints',
    ],
    'tables' => [
        'reporting_daily_metrics' => [
            'mode' => 'upsert',
            'identity' => [
                'metric_date',
                'metric_key',
                'metric_version',
                'dimension_hash',
            ],
            'preserve_id' => false,
            'order_by' => [
                'metric_date',
                'metric_key',
                'metric_version',
                'dimension_hash',
            ],
            'columns' => [
                'id',
                'metric_date',
                'metric_key',
                'metric_version',
                'dimension_hash',
                'dimensions',
                'numerator',
                'denominator',
                'projected_through',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'dimensions',
            ],
        ],
        'reporting_external_measurements' => [
            'mode' => 'upsert',
            'identity' => [
                'identity_hash',
            ],
            'preserve_id' => false,
            'order_by' => [
                'period_start',
                'period_end',
                'platform',
                'identity_hash',
            ],
            'columns' => [
                'id',
                'period_start',
                'period_end',
                'platform',
                'account_id',
                'account_timezone',
                'campaign_id',
                'group_id',
                'creative_id',
                'campaign_name',
                'group_name',
                'creative_name',
                'placement',
                'identity_quality',
                'currency',
                'impressions',
                'reach',
                'link_clicks',
                'outbound_clicks',
                'landing_page_views',
                'spend',
                'result_type',
                'results',
                'source',
                'source_file_hash',
                'meta',
                'identity_hash',
                'imported_at',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'meta',
            ],
        ],
    ],
];