<?php

return [
    'version' => 3,
    'optional' => true,
    'activation_tables' => [
        'reporting_sessions',
        'reporting_observations',
        'reporting_external_measurements',
        'reporting_daily_metrics',
        'reporting_projection_checkpoints',
        'reporting_scheduled_report_subscriptions',
        'reporting_scheduled_report_recipients',
    ],
    'tables' => [
        'reporting_scheduled_report_subscriptions' => [
            'mode' => 'upsert',
            'identity' => ['uuid'],
            'preserve_id' => false,
            'order_by' => ['report_key', 'name', 'uuid'],
            'columns' => [
                'id',
                'uuid',
                'report_key',
                'name',
                'channel',
                'days_of_week',
                'send_time',
                'timezone',
                'parameters',
                'is_enabled',
                'last_sent_at',
                'next_send_at',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'days_of_week',
                'parameters',
            ],
        ],
        'reporting_scheduled_report_recipients' => [
            'mode' => 'upsert',
            'identity' => [
                'scheduled_report_subscription_id',
                'recipient_type',
                'recipient_id',
            ],
            'preserve_id' => false,
            'order_by' => [
                'scheduled_report_subscription_id',
                'recipient_type',
                'recipient_id',
            ],
            'columns' => [
                'id',
                'scheduled_report_subscription_id',
                'recipient_type',
                'recipient_id',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'scheduled_report_subscription_id' => 'reporting_scheduled_report_subscriptions',
            ],
        ],
        'reporting_daily_metrics' => [
            'mode' => 'upsert',
            'identity' => [
                'metric_date',
                'metric_key',
                'metric_version',
                'dimension_hash',
            ],
            'preserve_id' => false,
            'order_by' => [
                'metric_date',
                'metric_key',
                'metric_version',
                'dimension_hash',
            ],
            'columns' => [
                'id',
                'metric_date',
                'metric_key',
                'metric_version',
                'dimension_hash',
                'dimensions',
                'numerator',
                'denominator',
                'projected_through',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'dimensions',
            ],
        ],
        'reporting_external_measurements' => [
            'mode' => 'upsert',
            'identity' => [
                'identity_hash',
            ],
            'preserve_id' => false,
            'order_by' => [
                'period_start',
                'period_end',
                'platform',
                'identity_hash',
            ],
            'columns' => [
                'id',
                'period_start',
                'period_end',
                'platform',
                'account_id',
                'account_timezone',
                'campaign_id',
                'group_id',
                'creative_id',
                'campaign_name',
                'group_name',
                'creative_name',
                'placement',
                'identity_quality',
                'currency',
                'impressions',
                'reach',
                'link_clicks',
                'outbound_clicks',
                'landing_page_views',
                'spend',
                'result_type',
                'results',
                'source',
                'source_file_hash',
                'meta',
                'identity_hash',
                'imported_at',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'meta',
            ],
        ],
    ],
];