<?php

return [
    'version' => 1,
    'optional' => true,
    'activation_tables' => [
        'scheduling_hosts',
        'bookable_services',
        'scheduling_availability_windows',
        'appointments',
        'appointment_attendees',
        'bookable_service_hosts',
        'appointment_lifecycle_events',
        'bookable_slot_offers',
        'booking_holds',
        'scheduling_resources',
        'scheduling_host_resources',
        'bookable_service_resource_requirements',
        'scheduling_resource_occupancies',
    ],
    'tables' => [
        'scheduling_hosts' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['sort_order', 'key'],
            'columns' => [
                'id',
                'key',
                'name',
                'status',
                'hostable_type',
                'hostable_id',
                'timezone',
                'capacity',
                'email',
                'phone',
                'sort_order',
                'source',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => ['meta'],
            'null_on_import' => [
                'hostable_type',
                'hostable_id',
            ],
        ],

        'bookable_services' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['sort_order', 'key'],
            'columns' => [
                'id',
                'key',
                'name',
                'description',
                'status',
                'duration_mode',
                'duration_minutes',
                'minimum_duration_minutes',
                'maximum_duration_minutes',
                'slot_interval_minutes',
                'buffer_before_minutes',
                'buffer_after_minutes',
                'minimum_notice_minutes',
                'booking_horizon_days',
                'cancellation_notice_minutes',
                'reschedule_notice_minutes',
                'timezone',
                'location_type',
                'location_details',
                'capacity',
                'requires_confirmation',
                'is_public',
                'sort_order',
                'source',
                'provider',
                'external_id',
                'external_url',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => [
                'location_details',
                'meta',
            ],
        ],

        'scheduling_resources' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['sort_order', 'key'],
            'columns' => [
                'id',
                'key',
                'name',
                'status',
                'source',
                'sort_order',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => ['meta'],
        ],

        'bookable_service_hosts' => [
            'mode' => 'upsert',
            'identity' => [
                'bookable_service_id',
                'scheduling_host_id',
            ],
            'preserve_id' => false,
            'order_by' => [
                'bookable_service_id',
                'sort_order',
                'scheduling_host_id',
            ],
            'columns' => [
                'id',
                'bookable_service_id',
                'scheduling_host_id',
                'is_active',
                'capacity_override',
                'sort_order',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'bookable_service_id' => 'bookable_services',
                'scheduling_host_id' => 'scheduling_hosts',
            ],
        ],

        'scheduling_host_resources' => [
            'mode' => 'upsert',
            'identity' => [
                'scheduling_host_id',
                'scheduling_resource_id',
            ],
            'preserve_id' => false,
            'order_by' => [
                'scheduling_host_id',
                'sort_order',
                'scheduling_resource_id',
            ],
            'columns' => [
                'id',
                'scheduling_host_id',
                'scheduling_resource_id',
                'capacity',
                'is_active',
                'source',
                'sort_order',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'scheduling_host_id' => 'scheduling_hosts',
                'scheduling_resource_id' => 'scheduling_resources',
            ],
        ],

        'bookable_service_resource_requirements' => [
            'mode' => 'upsert',
            'identity' => [
                'bookable_service_id',
                'scheduling_resource_id',
            ],
            'preserve_id' => false,
            'order_by' => [
                'bookable_service_id',
                'sort_order',
                'scheduling_resource_id',
            ],
            'columns' => [
                'id',
                'bookable_service_id',
                'scheduling_resource_id',
                'quantity',
                'is_active',
                'source',
                'sort_order',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'bookable_service_id' => 'bookable_services',
                'scheduling_resource_id' => 'scheduling_resources',
            ],
        ],

        'scheduling_availability_windows' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'bookable_service_id',
                'scheduling_host_id',
                'window_type',
                'timezone',
                'weekday',
                'start_time',
                'end_time',
                'starts_at',
                'ends_at',
                'capacity',
                'is_available',
                'source',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'bookable_service_id' => 'bookable_services',
                'scheduling_host_id' => 'scheduling_hosts',
            ],
        ],

        'appointments' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'bookable_service_id',
                'scheduling_host_id',
                'contact_id',
                'location_reference_type',
                'location_reference_id',
                'primary_attendee_type',
                'primary_attendee_id',
                'source_context_type',
                'source_context_id',
                'rescheduled_from_id',
                'idempotency_key',
                'status',
                'title',
                'description',
                'location_type',
                'location_details',
                'timezone',
                'starts_at',
                'ends_at',
                'confirmed_at',
                'completed_at',
                'no_show_at',
                'canceled_at',
                'cancellation_reason',
                'source',
                'created_by_type',
                'created_by_id',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => [
                'location_details',
                'meta',
            ],
            'references' => [
                'bookable_service_id' => 'bookable_services',
                'scheduling_host_id' => 'scheduling_hosts',
                'contact_id' => 'contacts',
            ],
            'deferred_references' => [
                'rescheduled_from_id' => 'appointments',
            ],
            'null_on_import' => [
                'location_reference_type',
                'location_reference_id',
                'created_by_type',
                'created_by_id',
            ],
            'polymorphic_references' => [
                [
                    'type_column' => 'primary_attendee_type',
                    'id_column' => 'primary_attendee_id',
                    'targets' => [
                        'App\\Modules\\Core\\Models\\Contact' => 'contacts',
                        'App\\Modules\\Core\\Models\\ContactImportBatch' => 'contact_import_batches',
                    ],
                ],
                [
                    'type_column' => 'source_context_type',
                    'id_column' => 'source_context_id',
                    'targets' => [
                        'App\\Modules\\Core\\Models\\Contact' => 'contacts',
                        'App\\Modules\\Core\\Models\\ContactImportBatch' => 'contact_import_batches',
                    ],
                ],
            ],
        ],

        'appointment_attendees' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'appointment_id',
                'attendee_type',
                'attendee_id',
                'contact_id',
                'name',
                'email',
                'phone',
                'role',
                'status',
                'responded_at',
                'joined_at',
                'canceled_at',
                'meta',
                'created_at',
                'updated_at',
                'deleted_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'appointment_id' => 'appointments',
                'contact_id' => 'contacts',
            ],
            'polymorphic_references' => [
                [
                    'type_column' => 'attendee_type',
                    'id_column' => 'attendee_id',
                    'targets' => [
                        'App\\Modules\\Core\\Models\\Contact' => 'contacts',
                        'App\\Modules\\Core\\Models\\ContactImportBatch' => 'contact_import_batches',
                    ],
                ],
            ],
        ],

        'appointment_lifecycle_events' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['occurred_at', 'id'],
            'columns' => [
                'id',
                'appointment_id',
                'event_id',
                'event_key',
                'from_status',
                'to_status',
                'actor_type',
                'actor_id',
                'source',
                'reason',
                'context',
                'occurred_at',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['context'],
            'references' => [
                'appointment_id' => 'appointments',
            ],
            'null_on_import' => [
                'actor_type',
                'actor_id',
            ],
        ],

        'scheduling_resource_occupancies' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'scheduling_resource_id',
                'scheduling_host_id',
                'appointment_id',
                'booking_hold_id',
                'quantity',
                'occupancy_starts_at',
                'occupancy_ends_at',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'scheduling_resource_id' => 'scheduling_resources',
                'scheduling_host_id' => 'scheduling_hosts',
                'appointment_id' => 'appointments',
            ],
            'null_on_import' => [
                'booking_hold_id',
            ],
        ],
    ],
];