<?php

return [
    'version' => 3,
    'tables' => [
        'webinar_schedule_profiles' => [
            'mode' => 'upsert',
            'identity' => ['key'],
            'preserve_id' => false,
            'order_by' => ['key'],
            'columns' => [
                'id',
                'key',
                'name',
                'description',
                'message_template_set_key',
                'status',
                'is_default',
                'is_active',
                'is_customized',
                'customized_at',
                'source',
                'source_config_path',
                'source_version',
                'last_synced_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
        ],

        'webinar_schedule_profile_items' => [
            'mode' => 'upsert',
            'identity' => [
                'webinar_schedule_profile_id',
                'key',
            ],
            'preserve_id' => false,
            'order_by' => [
                'webinar_schedule_profile_id',
                'sort_order',
                'id',
            ],
            'columns' => [
                'id',
                'webinar_schedule_profile_id',
                'key',
                'label',
                'context_key',
                'channel',
                'purpose',
                'scope',
                'surface',
                'message_type',
                'dispatch_key',
                'message_template_key',
                'source_config_path',
                'is_enabled',
                'is_active',
                'is_customized',
                'customized_at',
                'sort_order',
                'timing',
                'schedule',
                'conditions',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'schedule',
                'conditions',
                'meta',
            ],
            'references' => [
                'webinar_schedule_profile_id' => 'webinar_schedule_profiles',
            ],
        ],

        'webinar_series' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'slug',
                'title',
                'platform',
                'provider_event_type',
                'status',
                'webinar_schedule_profile_id',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'webinar_schedule_profile_id' => 'webinar_schedule_profiles',
            ],
        ],

        'webinars' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'webinar_series_id',
                'replacement_of_webinar_id',
                'webinar_schedule_profile_id',
                'title',
                'slug',
                'platform',
                'provider_event_type',
                'external_id',
                'host_account_key',
                'provider_lifecycle_status',
                'provider_missing_at',
                'provider_archived_at',
                'hidden_at',
                'hidden_reason',
                'join_url',
                'registration_url',
                'playback_token',
                'playback_url',
                'playback_passcode',
                'starts_at',
                'ends_at',
                'timezone',
                'description',
                'meta',
                'provider_settings',
                'created_at',
                'updated_at',
            ],
            'json_columns' => [
                'meta',
                'provider_settings',
            ],
            'references' => [
                'webinar_series_id' => 'webinar_series',
                'webinar_schedule_profile_id' => 'webinar_schedule_profiles',
            ],
            'deferred_references' => [
                'replacement_of_webinar_id' => 'webinars',
            ],
        ],

        'webinar_occurrence_suppressions' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'webinar_series_id',
                'platform',
                'provider_event_type',
                'external_id',
                'external_uuid',
                'reason',
                'suppressed_at',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'webinar_series_id' => 'webinar_series',
            ],
        ],

        'webinar_registrations' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'contact_id',
                'webinar_id',
                'replacement_of_registration_id',
                'join_token',
                'webinar_slug',
                'status',
                'source',
                'meta',
                'registered_at',
                'attended_at',
                'cancelled_at',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'contact_id' => 'contacts',
                'webinar_id' => 'webinars',
            ],
            'deferred_references' => [
                'replacement_of_registration_id' => 'webinar_registrations',
            ],
            'json_path_value_maps' => [
                'meta' => [
                    'registration_finalization.status' => [
                        'pending' => 'paused',
                        'queued' => 'paused',
                        'processing' => 'paused',
                    ],
                ],
            ],
            'resume_items' => [
                [
                    'category' => 'webinar_finalizations',
                    'json_column' => 'meta',
                    'path' => 'registration_finalization.status',
                    'statuses' => ['pending', 'queued', 'processing'],
                ],
            ],
        ],

        'webinar_registration_responses' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => [
                'webinar_registration_id',
                'sort_order',
                'id',
            ],
            'columns' => [
                'id',
                'webinar_registration_id',
                'question_key',
                'question_label',
                'question_type',
                'answer_key',
                'answer_label',
                'answer_text',
                'definition_version',
                'sort_order',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'webinar_registration_id' => 'webinar_registrations',
            ],
        ],

        'webinar_waitlist_signups' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => ['id'],
            'columns' => [
                'id',
                'contact_id',
                'webinar_series_id',
                'notified_at',
                'notification_mode',
                'expires_at',
                'ended_at',
                'source_page',
                'meta',
                'created_at',
                'updated_at',
            ],
            'json_columns' => ['meta'],
            'references' => [
                'contact_id' => 'contacts',
                'webinar_series_id' => 'webinar_series',
            ],
        ],

        'webinar_schedule_profile_chain_bindings' => [
            'mode' => 'upsert',
            'identity' => [
                'webinar_schedule_profile_id',
                'message_area_key',
            ],
            'preserve_id' => false,
            'order_by' => [
                'webinar_schedule_profile_id',
                'message_area_key',
                'id',
            ],
            'columns' => [
                'id',
                'webinar_schedule_profile_id',
                'key',
                'message_area_key',
                'message_chain_id',
                'dispatch_key',
                'surface',
                'is_active',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'webinar_schedule_profile_id' => 'webinar_schedule_profiles',
                'message_chain_id' => 'message_chains',
            ],
        ],

        'webinar_series_message_chain_bindings' => [
            'mode' => 'insert_empty',
            'preserve_id' => true,
            'order_by' => [
                'webinar_series_id',
                'message_area_key',
                'id',
            ],
            'columns' => [
                'id',
                'webinar_series_id',
                'key',
                'message_area_key',
                'message_chain_id',
                'dispatch_key',
                'surface',
                'is_active',
                'created_at',
                'updated_at',
            ],
            'references' => [
                'webinar_series_id' => 'webinar_series',
                'message_chain_id' => 'message_chains',
            ],
        ],
    ],
];